### PR TITLE
174 unit testing for user authentication

### LINKED ISSUE #174: Unit testing for user authentication
As a dev,
I would like to create unit testing for user authentication feature,
So that I can ensure the quality of the authentication features (sign up, sign in, sign out)

### PR DESCRIPTION
**Pull request by cl4414**
Simple frontend unit tests for the sign up, sign in, sign out feature.

### CODE REVIEW

**Comment by LamdaDev** [comment]
Hey Calvin, looking good so far. Can you document me on how you were able to run your unit tests on the frontend?

**Comment by cl4414** [comment]
To run the unit test on the frontend

1. cd to the frontend 
2. npm run test 
3. tests must passed like in the following pic

image

**Comment by cl4414** [comment]
> Hey Calvin, looking good so far. Can you document me on how you were able to run your unit tests on the frontend?

To run the unit test on the frontend

1. cd to the frontend
2. npm run test
3. tests must passed like in the following pic

image

**Review by LamdaDev — APPROVED** [review]
LGTM! Thanks for the documentation Calvin, make sure to copy that comment to your story so we can inform ourselves on how to run the tests!

Only thing I did notice when running the tests myself is that it shows the warning when setting up the DOM as below. We will fix them in a future patch

image

**Review by chrisanhthien — APPROVED** [review]
Great job!

**Pull request merged**
