### PR TITLE
Commit Last Second Hotfixes

### LINKED ISSUE #146: Commit Last Second Frontend Hotfixes
### Description
This User Story commits the last minute changes to the frontend bugfixes that were implemented for the demo.

- Fix text color of input field from white to black for readability
- Fix bug where teachers were able to rate students

### PR DESCRIPTION
**Pull request by LamdaDev**
- Fix text color of input field from white to black for readability
- Fix bug where teachers were able to rate students

### CODE REVIEW

**Review by JayC-SF — CHANGES_REQUESTED** [review]
amazing work

**Comment by JayC-SF** [comment]
im very satisfied

**Review by JayC-SF — APPROVED** [review]
just kidding :)

**Comment by LamdaDev** [comment]
> im very satisfied

just like my father 😭

**Comment by LamdaDev** [comment]
> not kidding

yippee

**Comment by JayC-SF** [comment]
im the jcpp

**Comment by LamdaDev** [comment]
bro is changing my comments like the ccp

**Pull request merged**
