### PR TITLE
Create Confirmation Button & Add Cooperation Questions for Rating Form

### LINKED ISSUE #115: Create Confirmation Button & Add Cooperation Questions for Rating Form
### Description

A confirmation button is required when submitting the Peer Assessment Form for User Friendly experience. It is one of the requirements. Additionally, after discussing, the frontend for the Cooperation Questions will be added into the form. Backend to track these changes requires a lot more work and will be explained in a separate issue

### PR DESCRIPTION
**Pull request by LamdaDev**
## Description

This PR serves to display a confirmation button when the logged in student presses submit to submit a new rating. The user will have to press on confirm before being able to create a new rating. If the user presses cancel, no rating will be made. Additionally, small but important bugs regarding the dropdown of the student list have been fixed. Finally, the frontend interface for the Cooperation Dimension have been added but unfortunately, the backend will require a lot more work.

## Demo

Animation2

## Features
- Added Confirmation Button when submitting the Rating Form
- Added frontend interface for Cooperation Assessment
- Bug fixes

### CODE REVIEW

**Review by JayC-SF — CHANGES_REQUESTED** [review]
It's amazing :0

**Comment by LamdaDev** [comment]
:D

**Review by JayC-SF — APPROVED** [review]
wow good job!

**Comment by JayC-SF** [comment]
No one blackmails me. Im alpha

**Pull request merged**
